//admin registration

POST http://localhost:8000/api/v1/admin
Content-Type: application/json 

{
    "fName":"Narayan",
    "lName":"Aryal",
    "email":"cr800@gmail.com",
    "phone":"021457",
    "address":"sydney",
    "password":"125445871qwe"
}

### login admin
POST http://localhost:8000/api/v1/admin/login
Content-Type: application/json 

{
    
    "email":"narayanaryal.code@gmail.com",
    "password":"Abc12345"
}



### category

###fetch category
GET  http://localhost:8000/api/v1/category



### product

POST http://localhost:8000/api/v1/product
Content-Type: application/json
Authorization: 63f168f311dea880032d2edd

{
    "name":"nike shoes",
    "description":"New shoes"
}