//admin registration

POST http://localhost:8000/api/v1/admin
Content-Type: application/json 

{
    "fName":"Narayan",
    "lName":"Aryal",
    "email":"cr800@gmail.com",
    "phone":"021457",
    "address":"sydney",
    "password":"125445871qwe"
}

### login admin
POST http://localhost:8000/api/v1/admin/login
Content-Type: application/json 

{
    
    "email":"narayanaryal.code@gmail.com",
    "password":"1234"
}